### ISSUE TITLE
Návrh GUI

### ISSUE THREAD

**Issue by lemichael** [walletcoach/walletcoach#3]

**Comment by marosgasparik** [comment]
![expenses by time](https://cloud.githubusercontent.com/assets/12121383/7551650/626b3980-f691-11e4-8b29-8f5b1f5387da.png)
![new company](https://cloud.githubusercontent.com/assets/12121383/7551649/626b314c-f691-11e4-9903-0173fdb43573.png)
![new expense](https://cloud.githubusercontent.com/assets/12121383/7551648/6269f2e6-f691-11e4-93f8-caa6295398a3.png)
